services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5000 -m flask run --no-debug"
      ]