"""Initial migration

Revision ID: 969dd7e2c720
Revises: 
Create Date: 2026-08-27 04:21:10.706470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969dd7e2c720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_tags', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
